################################################################################
# Jupyter Book configuration for the Pyomo Tutorial notebooks
# Docs: https://jupyterbook.org/en/stable/customize/config.html
################################################################################

title: "Pyomo Tutorial"
author: SECQUOIA Research Group
copyright: "2026"
logo: media/Pyomo-logo.png
exclude_patterns: [.DS_Store, ".venv", "_build", "**.ipynb_checkpoints", "**.pytest_cache", "tools"]

repository:
  url: https://github.com/SECQUOIA/pyomo-summer-ws
  path_to_book: .
  branch: main

execute:
  execute_notebooks: "off"

latex:
  latex_documents:
    targetname: Pyomo-Tutorial.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: false
  use_multitoc_numbering: false
  extra_navbar: |
    Built with <a href="https://jupyterbook.org/">Jupyter Book</a>.
  analytics:
    google_analytics_id: G-DVQ7NZ8CYZ

launch_buttons:
  colab_url: https://colab.research.google.com

sphinx:
  config:
    html_show_copyright: false
    suppress_warnings:
      - "myst.xref_missing"
